[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
bytes = "1.0.1"
reqwest = {version = "0.11.3", features = ["json", "blocking", "stream"] }
roxmltree = "0.14.1"
serde = {version = "1.0.130", features = ["derive"] }
tokio = {version = "1.7.0", features = ["full"] }
tokio-util = {version = "0.6.1", features = ["io"] }
xmlparser = "0.13.3"
futures-util = "0.3.19"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
